"""add_project_type_and_currency

Revision ID: 05ffdf1ea5e5
Revises: 6743d884d418
Create Date: 2026-05-28 12:46:37.730988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ffdf1ea5e5'
down_revision: Union[str, Sequence[str], None] = '6743d884d418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('original_currency', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('exchange_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'exchange_rate')
    op.drop_column('transactions', 'original_currency')
    op.drop_column('projects', 'type')
    op.drop_column('accounts', 'currency')
    # ### end Alembic commands ###
