"""add_proactive_insights_dispatch_flags

Revision ID: 0fbd17760df2
Revises: 98b745009fe2
Create Date: 2026-06-16 14:43:36.443458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbd17760df2'
down_revision: Union[str, Sequence[str], None] = '98b745009fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('proactive_insights_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('proactive_insights_whatsapp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'proactive_insights_whatsapp')
    op.drop_column('users', 'proactive_insights_email')
    # ### end Alembic commands ###
