"""add_project_type_and_currency_final

Revision ID: 15eb066b02a3
Revises: 05ffdf1ea5e5
Create Date: 2026-05-28 12:49:09.497537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15eb066b02a3'
down_revision: Union[str, Sequence[str], None] = '05ffdf1ea5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
