"""add_type_to_project_item

Revision ID: 17ad21cfd60b
Revises: 253abab3747c
Create Date: 2026-06-01 03:30:26.698769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ad21cfd60b'
down_revision: Union[str, Sequence[str], None] = '253abab3747c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_items', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_items', 'type')
    # ### end Alembic commands ###
