"""add_push_notifications_flag

Revision ID: 1bfd28db1c16
Revises: 15eb066b02a3
Create Date: 2026-05-28 13:14:12.413366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfd28db1c16'
down_revision: Union[str, Sequence[str], None] = '15eb066b02a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_notifications_enabled')
    # ### end Alembic commands ###
