"""add_notification_preference_flags

Revision ID: 253abab3747c
Revises: 62067bf7c06b
Create Date: 2026-06-01 02:37:53.277338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253abab3747c'
down_revision: Union[str, Sequence[str], None] = '62067bf7c06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spending_alerts_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('market_insights_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'market_insights_enabled')
    op.drop_column('users', 'spending_alerts_enabled')
    # ### end Alembic commands ###
