"""add_proactive_insights_minute

Revision ID: 5e80bbbb35eb
Revises: a3dfb74c2025
Create Date: 2026-06-16 01:17:44.339120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e80bbbb35eb'
down_revision: Union[str, Sequence[str], None] = 'a3dfb74c2025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('proactive_insights_minute', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'proactive_insights_minute')
    # ### end Alembic commands ###
