"""add_goal_id_to_transaction

Revision ID: 62067bf7c06b
Revises: 98e6101aaff4
Create Date: 2026-06-01 02:03:00.357930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62067bf7c06b'
down_revision: Union[str, Sequence[str], None] = '98e6101aaff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'goal_id')
    # ### end Alembic commands ###
