"""add_project_to_transactions

Revision ID: 6eb0b154c426
Revises: 701a4199e334
Create Date: 2026-05-26 21:36:03.527406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb0b154c426'
down_revision: Union[str, Sequence[str], None] = '701a4199e334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('project_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('budget_allocation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_items_id'), 'project_items', ['id'], unique=False)
    op.add_column('transactions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('project_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'project_items', ['project_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'project_item_id')
    op.drop_column('transactions', 'project_id')
    op.drop_index(op.f('ix_project_items_id'), table_name='project_items')
    op.drop_table('project_items')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
