"""add_is_active_to_categories

Revision ID: 701a4199e334
Revises: 5bac2c4b1d42
Create Date: 2026-05-26 16:25:09.715589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701a4199e334'
down_revision: Union[str, Sequence[str], None] = '5bac2c4b1d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
