"""initial_migration

Revision ID: 7033791def1c
Revises: 
Create Date: 2026-05-26 01:03:59.328002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7033791def1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('goals', 'target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.alter_column('goals', 'target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('goals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
