"""add_business_fields

Revision ID: 98e6101aaff4
Revises: 9f68e91f3083
Create Date: 2026-06-01 01:02:55.783472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e6101aaff4'
down_revision: Union[str, Sequence[str], None] = '9f68e91f3083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_business', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('cnpj', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('logo_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('projects', 'logo_path')
    op.drop_column('projects', 'cnpj')
    op.drop_column('projects', 'is_business')
    # ### end Alembic commands ###
