"""add_proactive_insights_config

Revision ID: a3dfb74c2025
Revises: a28863642867
Create Date: 2026-06-15 23:11:58.461049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dfb74c2025'
down_revision: Union[str, Sequence[str], None] = 'a28863642867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('proactive_insights_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('proactive_insights_days', sa.String(), nullable=True))
    op.add_column('users', sa.Column('proactive_insights_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'proactive_insights_hour')
    op.drop_column('users', 'proactive_insights_days')
    op.drop_column('users', 'proactive_insights_enabled')
    # ### end Alembic commands ###
