"""add_user_active_and_ai_tokens

Revision ID: ff2ac0615a1c
Revises: 0fbd17760df2
Create Date: 2026-06-18 13:50:18.682545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2ac0615a1c'
down_revision: Union[str, Sequence[str], None] = '0fbd17760df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ai_tokens_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_tokens_used')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
